version: "3.5"

services:
  db:
    image: postgres:10.1-alpine
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo